apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ram-deployment
  namespace: default
  labels:
    run: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: my-app
  template:
    metadata:
      labels:
        run: my-app
        name: my-ram-pod
        namespace: default
    spec:
      containers:
      - name: my-container
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: my-ram-service
spec:
  selector:
    run: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
