appConfig: value
pod:
  name: my-helm-pod
  image: nginx:latest
service:
  name: my-helm-service
  port: 80
nad:
  name: my-helm-macvlan
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [{"dst": "0.0.0.0/0"}],
        "gateway": "192.168.1.1"
      }
    }
