apiVersion: v1
kind: ConfigMap
metadata:
  name: set-namespace-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-fn/set-namespace:v0.1
  namespace: my
  labels:
    app: foo
data:
  namespace: my-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: set-labels-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-fn/set-labels:v0.1
  namespace: my
  labels:
    app: foo
data:
  app: foo
