apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  annotations:
    k8s.v1.cni.cncf.io/networks: my-macvlan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        name: my-pod
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        env:
        - name: APP_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_CONFIG
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
